server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/bc-finances}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    validate-on-migrate: false

bc-finances:
  origin-permitted: http://localhost:4200
  i18n:
    cache-seconds: 0
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
  s3:
    access-key-id: ${AWS_S3_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY:}
    bucket: ${AWS_S3_BUCKET:}