server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
  datasource:
    url: ${env.DB_URL:jdbc:postgresql://localhost:5435/bc-finances}
    username: ${env.DB_USERNAME:postgres}
    password: ${env.DB_PASSWORD:postgres}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  flyway:
    validate-on-migrate: false
    ignore-missing-migrations: true

bcfinances:
  origin-permitted: http://localhost:4200
  i18n:
    cache-seconds: 0
  mail:
    host: ${env.MAIL_HOST}
    port: ${env.MAIL_PORT}
    username: ${env.MAIL_USERNAME}
    password: ${env.MAIL_PASSWORD}
  s3:
    access-key-id: ${env.AWS_S3_ACCESS_KEY_ID}
    secret-access-key: ${env.AWS_S3_SECRET_ACCESS_KEY}
    bucket: ${env.AWS_S3_BUCKET}
  security:
    front-end-client: ${env.FRONT_END_CLIENT}
    front-end-password: ${env.FRONT_END_PASSWORD}
    mobile-client: ${env.MOBILE_CLIENT}
    mobile-password: ${env.MOBILE_PASSWORD}