spring:
  flyway:
    validate-on-migrate: true

otel:
  resource:
    attributes:
      deployment.environment: prod
      host.name: prod
  traces:
    sampler: parentbased_traceidratio
    sampler.arg: 0.05
  logs:
    exporter: none

bc-finances:
  origin-permitted: https://bc-finances.up.railway.app
  i18n:
    cache-seconds: -1
